"""Untouched one-shot acceptance set for structural intent-router v3."""

FINAL_INTENT_CASES_V3 = [
    # procedural (20)
    ("how would I fit the UV510 into a nineteen-inch rack", "procedural"),
    ("give me directions for wiring the DC input", "procedural"),
    ("what procedure changes the operating channel", "procedural"),
    ("walk through attaching the coaxial feed", "procedural"),
    ("steps for restoring PK940 default configuration", "procedural"),
    ("how can the speaker volume be adjusted", "procedural"),
    ("show me how the protective cover comes off", "procedural"),
    ("installation method for a replacement fan", "procedural"),
    ("what sequence enables repeater operation", "procedural"),
    ("guide me in connecting the earth terminal", "procedural"),
    ("how should the antenna bracket be positioned", "procedural"),
    ("instructions to enter a new IP configuration", "procedural"),
    ("tell me the process used to lock the controls", "procedural"),
    ("how do you safely remove the power lead", "procedural"),
    ("procedure for installing UV510 on a wall", "procedural"),
    ("what must be done to select low output power", "procedural"),
    ("need a step by step cabinet setup", "procedural"),
    ("how can I exchange the duplexer module", "procedural"),
    ("plese explain how to swich analog mode on", "procedural"),
    ("method to verify the installation after startup", "procedural"),

    # troubleshooting (20)
    ("UV510 powers up but cannot transmit", "troubleshooting"),
    ("why is warning code G6 displayed", "troubleshooting"),
    ("received speech has become badly distorted", "troubleshooting"),
    ("PK940 loses power whenever the fan starts", "troubleshooting"),
    ("the antenna port is not recognized anymore", "troubleshooting"),
    ("coverage varies from one minute to the next", "troubleshooting"),
    ("all front controls have stopped responding", "troubleshooting"),
    ("screen remains blank after the device boots", "troubleshooting"),
    ("transmit LED flashes without RF output", "troubleshooting"),
    ("what causes the temperature fault to recur", "troubleshooting"),
    ("the network interface keeps going offline", "troubleshooting"),
    ("unit restarts when a call begins", "troubleshooting"),
    ("there is a constant buzzing in the speaker", "troubleshooting"),
    ("why are channel indicators permanently illuminated", "troubleshooting"),
    ("forward signal strength has fallen sharply", "troubleshooting"),
    ("RX works while TX remains completely inactive", "troubleshooting"),
    ("cooling fan produces a grinding noise", "troubleshooting"),
    ("repeatr shows garbled text on its display", "troubleshooting"),
    ("fuse opens each time the unit is switched on", "troubleshooting"),
    ("no ethernet activity despite a connected cable", "troubleshooting"),

    # comparison (20)
    ("UV510 vs PK940 for a low-power indoor site", "comparison"),
    ("which of these two repeaters is physically smaller", "comparison"),
    ("are the supplied cables the same for each model", "comparison"),
    ("contrast their supported frequency bands", "comparison"),
    ("does UV510 have features missing from PK940", "comparison"),
    ("which unit would be preferable for rack use", "comparison"),
    ("compare UV510 and PK940 power requirements", "comparison"),
    ("does one product tolerate more heat than the other", "comparison"),
    ("how different are their grounding arrangements", "comparison"),
    ("list what comes with each of the two devices", "comparison"),
    ("which repeater delivers greater transmit power", "comparison"),
    ("do both models use equivalent wall brackets", "comparison"),
    ("PK940 against UV510 for outdoor deployment", "comparison"),
    ("what makes the first unit distinct from the second", "comparison"),
    ("are their alarm code systems identical", "comparison"),
    ("choose the better option for battery backup", "comparison"),
    ("compare weight dimensions and connector count", "comparison"),
    ("which member of this pair is simpler to maintain", "comparison"),
    ("do these products provide equal weather protection", "comparison"),
    ("comparision of UV510 and PK940 package contents", "comparison"),

    # standard (20)
    ("what supply current is specified for UV510", "standard"),
    ("does PK940 include a grounding strap", "standard"),
    ("how many status indicators are fitted", "standard"),
    ("name the connector located above the fan", "standard"),
    ("is UV510 certified to IP55", "standard"),
    ("state the acceptable ambient temperature", "standard"),
    ("which manufacturer produces PK940", "standard"),
    ("can this unit be installed in a cabinet", "standard"),
    ("list the screws contained in the package", "standard"),
    ("is a dedicated transmit antenna socket provided", "standard"),
    ("give the selectable output levels", "standard"),
    ("what does the green operation light indicate", "standard"),
    ("may alcohol be applied to the enclosure", "standard"),
    ("where is the chassis serial label", "standard"),
    ("does the standard package contain a fuse", "standard"),
    ("what is the distinction between RX and TX indicators", "standard"),
    ("maximum programmable channel count", "standard"),
    ("does it meet the stated EMC regulation", "standard"),
    ("wht are the dimensions of UV510", "standard"),
    ("can both timeslots receive simultaneously", "standard"),
]
