"""Training data for the deterministic intent classifier.

Separate from routing/test_intent_cases.py (no phrase overlap) so the test set
measures generalization. Mostly generic phrasings (few specific model names) so
the classifier keys on question SHAPE, not product identity.

~60 examples per class, targeting three weaknesses seen in evaluation:
  1. Traps: "difference"/"these"/"both"/"two" in NON-comparison questions.
  2. troubleshooting vs procedural boundary (symptom vs how-to).
  3. standard breadth (factual, capability, existence, yes/no).

Intents: standard, procedural, comparison, troubleshooting.
"""

TRAIN_DATA = [
    # ═══════════ procedural: how-to tasks, no symptom ═══════════
    ("how do I set up the repeater", "procedural"),
    ("how to install a digital repeater", "procedural"),
    ("how do I mount this on a rack", "procedural"),
    ("how do I configure the channel", "procedural"),
    ("how do I adjust the volume", "procedural"),
    ("how do I connect the antenna", "procedural"),
    ("what are the steps to set it up", "procedural"),
    ("guide me through installation", "procedural"),
    ("how do I attach the bracket", "procedural"),
    ("how do I ground the repeater", "procedural"),
    ("walk me through mounting it", "procedural"),
    ("how do I power it on", "procedural"),
    ("procedure for installing the duplexer", "procedural"),
    ("how do I set it up and then check it works", "procedural"),
    ("how do I wall mount the unit", "procedural"),
    ("how to change the channel", "procedural"),
    ("how do I lock the repeater", "procedural"),
    ("what is the installation procedure", "procedural"),
    ("show me how to replace the cover", "procedural"),
    ("how do I turn on the backlight", "procedural"),
    ("how to fit it into a cabinet", "procedural"),
    ("how do I connect the power cord", "procedural"),
    ("how do I install and configure it", "procedural"),
    ("steps for wall mounting", "procedural"),
    ("how do I remove the bottom cover", "procedural"),
    ("how do I adjust the power level", "procedural"),
    ("how to set the volume", "procedural"),
    ("how do I install the antenna and feed line", "procedural"),
    ("how do I perform post installation checks", "procedural"),
    ("how do I mount it and ground it", "procedural"),
    ("what is the correct way to install it", "procedural"),
    ("how should I connect the cables", "procedural"),
    ("explain how to set up the device", "procedural"),
    ("how do I assemble the unit", "procedural"),
    ("how do I fix it to the wall", "procedural"),
    ("how to enable transmit mode", "procedural"),
    ("how do I switch channels", "procedural"),
    ("how do I unlock the keypad", "procedural"),
    ("tell me how to mount the repeater", "procedural"),
    ("how to wire the power supply", "procedural"),
    ("how do I set the frequency", "procedural"),
    ("how do I position the antenna", "procedural"),
    ("what steps are needed for setup", "procedural"),
    ("how do I prepare the tools for installation", "procedural"),
    ("how do I secure it in the rack", "procedural"),
    ("how do I turn the repeater off", "procedural"),
    ("how do I replace the duplexer unit", "procedural"),
    ("how to do the initial configuration", "procedural"),
    ("how do I install it step by step", "procedural"),
    ("how do I check the power supply before install", "procedural"),
    # Single-entity examples balance the normalized MODEL feature.
    ("how do I install AX500", "procedural"),
    ("steps to mount BX700", "procedural"),
    ("how to configure NX400", "procedural"),
    ("turn on XR200 step by step", "procedural"),
    ("how do I ground TX900", "procedural"),
    ("procedure to clean RX800", "procedural"),
    ("how should I connect Alpha300", "procedural"),
    ("set up Beta600 in a cabinet", "procedural"),
    ("how to replace the cover on Delta10", "procedural"),
    ("show me how to power off Gamma20", "procedural"),
    # Broader imperative/process phrasings.
    ("what do I need to do to enable digital mode", "procedural"),
    ("what is the process for programming a frequency", "procedural"),
    ("describe the method used to change a channel", "procedural"),
    ("instructions for attaching an RF connector", "procedural"),
    ("give the sequence for removing the control panel", "procedural"),
    ("help me update the network address", "procedural"),
    ("procedure needed to activate the transmitter", "procedural"),
    ("how can the operating mode be selected", "procedural"),
    ("walk through replacing a damaged fuse", "procedural"),
    ("what actions configure the audio level", "procedural"),
    ("method for securing the equipment to rails", "procedural"),
    ("show the correct shutdown sequence", "procedural"),
    ("explain how the software settings are updated", "procedural"),
    ("steps needed before powering the device", "procedural"),
    ("tell me the way to connect an external supply", "procedural"),

    # ═══════════ troubleshooting: symptom or fault present ═══════════
    ("alarm code is showing", "troubleshooting"),
    ("what does this alarm mean", "troubleshooting"),
    ("the indicator turned red", "troubleshooting"),
    ("it won't power up", "troubleshooting"),
    ("device is beeping constantly", "troubleshooting"),
    ("signal is weak", "troubleshooting"),
    ("the fan stopped working", "troubleshooting"),
    ("getting an over voltage warning", "troubleshooting"),
    ("nothing is transmitting", "troubleshooting"),
    ("the screen shows an error", "troubleshooting"),
    ("why is it not working", "troubleshooting"),
    ("it stopped responding", "troubleshooting"),
    ("what should I check if it fails to start", "troubleshooting"),
    ("the light keeps blinking", "troubleshooting"),
    ("there is a fault on the display", "troubleshooting"),
    ("it will not turn on", "troubleshooting"),
    ("the repeater is not powering on", "troubleshooting"),
    ("coverage is poor", "troubleshooting"),
    ("the range dropped suddenly", "troubleshooting"),
    ("i see error E3", "troubleshooting"),
    ("alarm indicator is flashing red", "troubleshooting"),
    ("no signal is coming through", "troubleshooting"),
    ("the device overheats", "troubleshooting"),
    ("transmission keeps failing", "troubleshooting"),
    ("why does it show an under voltage alarm", "troubleshooting"),
    ("what causes the vswr alarm", "troubleshooting"),
    ("the unit keeps shutting down", "troubleshooting"),
    ("my repeater has stopped working", "troubleshooting"),
    ("the audio is distorted", "troubleshooting"),
    ("what to do when the fan fails", "troubleshooting"),
    ("the power led is off", "troubleshooting"),
    ("it keeps restarting on its own", "troubleshooting"),
    ("there is no audio output", "troubleshooting"),
    ("the repeater won't respond to input", "troubleshooting"),
    ("why is the signal dropping", "troubleshooting"),
    ("i am getting a temperature alarm", "troubleshooting"),
    ("the display is frozen", "troubleshooting"),
    ("it shuts off after a few minutes", "troubleshooting"),
    ("why is there interference", "troubleshooting"),
    ("the transmit light does not come on", "troubleshooting"),
    ("i hear a buzzing noise from it", "troubleshooting"),
    ("the alarm keeps sounding", "troubleshooting"),
    ("what does a red status light indicate", "troubleshooting"),
    ("it fails to establish a connection", "troubleshooting"),
    ("the repeater dropped offline", "troubleshooting"),
    ("power keeps cutting out", "troubleshooting"),
    ("why won't it start up", "troubleshooting"),
    ("the fan is making a strange noise", "troubleshooting"),
    ("reception has gotten worse", "troubleshooting"),
    ("the unit is completely dead", "troubleshooting"),
    # Single-entity examples balance the normalized MODEL feature.
    ("AX500 will not start", "troubleshooting"),
    ("BX700 shows an alarm", "troubleshooting"),
    ("poor coverage on NX400", "troubleshooting"),
    ("XR200 keeps restarting", "troubleshooting"),
    ("TX900 has no audio", "troubleshooting"),
    ("RX800 is overheating", "troubleshooting"),
    ("Alpha300 displays error E3", "troubleshooting"),
    ("Beta600 stopped transmitting", "troubleshooting"),
    ("the fan failed on Delta10", "troubleshooting"),
    ("Gamma20 has a flashing red light", "troubleshooting"),
    # Component-state and degraded-behavior phrasings.
    ("the network socket is no longer recognized", "troubleshooting"),
    ("both channel lights remain permanently lit", "troubleshooting"),
    ("the grounding alarm appears after boot", "troubleshooting"),
    ("receive audio cuts in and out", "troubleshooting"),
    ("the display remains dark although power is present", "troubleshooting"),
    ("a connector is not detected by the unit", "troubleshooting"),
    ("the status indicators are frozen", "troubleshooting"),
    ("output has become weaker over time", "troubleshooting"),
    ("the system hangs during initialization", "troubleshooting"),
    ("calls drop whenever transmission begins", "troubleshooting"),
    ("the device reports a ground fault", "troubleshooting"),
    ("why are the indicators stuck on", "troubleshooting"),
    ("the RF port stopped responding", "troubleshooting"),
    ("sound disappears after several minutes", "troubleshooting"),
    ("power is present but controls do not respond", "troubleshooting"),

    # ═══════════ comparison: compare products (two/multiple) ═══════════
    ("compare these two models", "comparison"),
    ("how do these two devices compare", "comparison"),
    ("what sets these two apart", "comparison"),
    ("difference between the two units", "comparison"),
    ("which model is preferable", "comparison"),
    ("are these two units the same", "comparison"),
    ("contrast the two repeaters", "comparison"),
    ("which of these two should I pick", "comparison"),
    ("do the two share the same features", "comparison"),
    ("how do they stack up against each other", "comparison"),
    ("comparsion of the two devices", "comparison"),
    ("whats the diference between the two units", "comparison"),
    ("which is superior of the two", "comparison"),
    ("compare one against the other", "comparison"),
    ("how does the first compare to the second", "comparison"),
    ("which repeater is better between them", "comparison"),
    ("compare the two on installation", "comparison"),
    ("compare the two on power output", "comparison"),
    ("do both units include the same parts", "comparison"),
    ("what differs between the two devices", "comparison"),
    ("which one wins in a comparison", "comparison"),
    ("pick the better of the two for me", "comparison"),
    ("compare their alarm handling", "comparison"),
    ("which of the two has better specs", "comparison"),
    ("versus comparison of both units", "comparison"),
    ("how do the two models differ from each other", "comparison"),
    ("put the two side by side", "comparison"),
    ("which should I buy between these two", "comparison"),
    ("what are the differences between the two repeaters", "comparison"),
    ("compare and contrast the two units", "comparison"),
    ("which of the two is more suitable", "comparison"),
    ("tell me how they differ", "comparison"),
    ("compare the specifications of both", "comparison"),
    ("which one is the better choice of the two", "comparison"),
    ("do the two differ in mounting", "comparison"),
    ("how do their features compare", "comparison"),
    ("compare the two devices for me", "comparison"),
    ("which has the edge between them", "comparison"),
    ("what makes one better than the other", "comparison"),
    ("compare installation between the two", "comparison"),
    ("which of the pair should i choose", "comparison"),
    ("show a comparison of both units", "comparison"),
    ("how similar are the two devices", "comparison"),
    ("which model beats the other", "comparison"),
    ("weigh the two against each other", "comparison"),
    ("compare their power outputs", "comparison"),
    ("do they compare well to one another", "comparison"),
    ("which of these two performs better", "comparison"),
    ("give me a side by side of the two", "comparison"),
    ("what distinguishes the two products", "comparison"),
    # Entity-based comparisons: teach structure without corpus product names.
    ("AX500 vs BX700", "comparison"),
    ("NX400 versus XR200", "comparison"),
    ("compare model A100 with model B200", "comparison"),
    ("which is better TX900 or RX800", "comparison"),
    ("what differs between Alpha300 and Beta600", "comparison"),
    ("how is Delta10 different from Gamma20", "comparison"),
    ("do the two models include identical accessories", "comparison"),
    ("are the supplied components the same for both units", "comparison"),
    ("does each repeater ship with matching mounting hardware", "comparison"),
    ("which device comes with more accessories", "comparison"),
    # Relational phrasing without explicit compare/versus keywords.
    ("contrast their power connectors", "comparison"),
    ("show differences in weight across both products", "comparison"),
    ("do these units require equal supply voltage", "comparison"),
    ("are their maintenance instructions equivalent", "comparison"),
    ("what benefits does one model have over the other", "comparison"),
    ("how do their status displays differ", "comparison"),
    ("which unit is more appropriate for a desk installation", "comparison"),
    ("do they follow an identical startup process", "comparison"),
    ("which of these models supports more channels", "comparison"),
    ("is one package more complete than the other", "comparison"),
    ("does each product use the same antenna connector", "comparison"),
    ("which device offers greater environmental protection", "comparison"),
    ("are the specifications equal across the pair", "comparison"),
    ("tell me whether their supplied parts differ", "comparison"),
    ("what separates the first product from the second", "comparison"),

    # ═══════════ standard: factual, capability, existence, yes/no ═══════════
    ("what is the frequency range", "standard"),
    ("list the box contents", "standard"),
    ("what ports does it have", "standard"),
    ("is it dust resistant", "standard"),
    ("does it support bluetooth", "standard"),
    ("can it run on battery", "standard"),
    ("what is the weight", "standard"),
    ("what accessories are included", "standard"),
    ("what is the maximum power", "standard"),
    ("tell me the voltage rating", "standard"),
    ("what temperature can it handle", "standard"),
    ("what is the model number", "standard"),
    ("does it come with a power cord", "standard"),
    ("what certifications does it have", "standard"),
    ("what are the output power levels", "standard"),
    ("what connectors are on the rear panel", "standard"),
    ("what is the difference between high and low power", "standard"),
    ("what is the difference between digital and analog mode", "standard"),
    ("what is the difference between the two timeslots", "standard"),
    ("who makes these repeaters", "standard"),
    ("who manufactures these units", "standard"),
    ("where are these devices produced", "standard"),
    ("what are the two antenna connectors", "standard"),
    ("can the two timeslots transmit simultaneously", "standard"),
    ("what do both indicators mean", "standard"),
    ("how many connectors are on the back", "standard"),
    ("is the unit waterproof", "standard"),
    ("does it have an ethernet port", "standard"),
    ("can I clean it with alcohol", "standard"),
    ("is it rated for outdoor use", "standard"),
    ("what is the operating voltage range", "standard"),
    ("what is the default password", "standard"),
    ("how much does it weigh", "standard"),
    ("what is the antenna connector type", "standard"),
    ("what is the dimension of the unit", "standard"),
    ("what input voltage does it need", "standard"),
    ("what is the channel spacing", "standard"),
    ("does it have a display screen", "standard"),
    ("what materials is it made of", "standard"),
    ("what is the power consumption", "standard"),
    ("what frequency bands are supported", "standard"),
    ("is there a warranty included", "standard"),
    ("what is the rated current", "standard"),
    ("what comes inside the package", "standard"),
    ("what are the two power supply options", "standard"),
    ("what is the difference between the basic and advanced version", "standard"),
    ("who is the manufacturer of these products", "standard"),
    ("does it include mounting screws", "standard"),
    ("what is the maximum operating temperature", "standard"),
    ("can it be powered over ethernet", "standard"),
    # Single-entity examples balance the normalized MODEL feature.
    ("what is the power of AX500", "standard"),
    ("does BX700 have wifi", "standard"),
    ("what comes with NX400", "standard"),
    ("is XR200 waterproof", "standard"),
    ("what voltage does TX900 need", "standard"),
    ("how much does RX800 weigh", "standard"),
    ("what ports are on Alpha300", "standard"),
    ("does Beta600 include a battery", "standard"),
    ("what frequency range supports Delta10", "standard"),
    ("who manufactures Gamma20", "standard"),
    # Factual imperatives, availability, suitability, and compliance.
    ("is a power cable supplied with the unit", "standard"),
    ("how many frequencies can be programmed", "standard"),
    ("name the controls located on the front", "standard"),
    ("list every component in the shipping box", "standard"),
    ("is the product suitable for a humid room", "standard"),
    ("is detergent permitted during cleaning", "standard"),
    ("does the equipment comply with IP65", "standard"),
    ("state the number of antenna ports", "standard"),
    ("are both connectors female type N", "standard"),
    ("which accessories are supplied", "standard"),
    ("give the material used for the enclosure", "standard"),
    ("is wall mounting supported", "standard"),
    ("how many indicators are provided", "standard"),
    ("does it meet the stated safety standard", "standard"),
    ("is solvent allowed for product care", "standard"),
]

# The first one-shot acceptance set was rejected (macro-F1=0.825). Once its
# result had been inspected it ceased to be a valid test set, so its labeled
# examples are now legitimate training data for the next model version.
from routing.retired_intent_diagnostic_cases import RETIRED_INTENT_CASES
from routing.retired_intent_diagnostic_cases_v2 import RETIRED_INTENT_CASES_V2

TRAIN_DATA.extend(RETIRED_INTENT_CASES)
TRAIN_DATA.extend(RETIRED_INTENT_CASES_V2)
