"""Retired v1 acceptance set for the deterministic intent router.

The v1 router scored macro-F1=0.825 and failed acceptance. These labeled cases
are now training data for v2 and must never be reported as final evaluation.
"""

RETIRED_INTENT_CASES = [
    # procedural (30)
    ("walk me through fitting the DR450 into a rack", "procedural"),
    ("instructions for connecting the RF cable", "procedural"),
    ("how should the grounding lead be attached", "procedural"),
    ("show the sequence for replacing a power module", "procedural"),
    ("what do I do to activate analog mode", "procedural"),
    ("help me program a new channel", "procedural"),
    ("steps required to remove the front panel", "procedural"),
    ("explain the correct antenna installation", "procedural"),
    ("how can I fasten the MR850 to its bracket", "procedural"),
    ("procedure to shut down the base station safely", "procedural"),
    ("tell me the proper way to insert the fuse", "procedural"),
    ("how can the external supply be wired", "procedural"),
    ("guide for changing from digital to analog", "procedural"),
    ("what is the process for updating the channel settings", "procedural"),
    ("mounting steps for a CR720 repeater", "procedural"),
    ("how should I prepare the device before cleaning", "procedural"),
    ("teach me to connect a duplexer", "procedural"),
    ("initial setup procedure for the BR310", "procedural"),
    ("how can I secure all feed lines", "procedural"),
    ("which steps put the unit into transmit mode", "procedural"),
    ("installation sequence for the grounding kit", "procedural"),
    ("how do you detach the upper housing", "procedural"),
    ("tell me how the cabinet rails are installed", "procedural"),
    ("what must I do to configure the IP address", "procedural"),
    ("how can I switch the display illumination on", "procedural"),
    ("plese show me how to instal the DR450", "procedural"),
    ("need steps for antenna setup", "procedural"),
    ("connect power then verify startup procedure", "procedural"),
    ("how to correctly torque the mounting screws", "procedural"),
    ("describe the method for changing the output level", "procedural"),

    # troubleshooting (30)
    ("DR450 reports an overheat warning", "troubleshooting"),
    ("there is silence even though the receive light is on", "troubleshooting"),
    ("why does the fuse blow after startup", "troubleshooting"),
    ("my coverage became intermittent", "troubleshooting"),
    ("error H7 appeared on the screen", "troubleshooting"),
    ("the cooling fan runs unusually slowly", "troubleshooting"),
    ("MR850 cannot establish a link", "troubleshooting"),
    ("transmit power is lower than expected", "troubleshooting"),
    ("the receiver produces crackling audio", "troubleshooting"),
    ("why is the voltage indicator blinking", "troubleshooting"),
    ("the unit starts but immediately powers down", "troubleshooting"),
    ("no channels appear after boot", "troubleshooting"),
    ("CR720 displays a high VSWR condition", "troubleshooting"),
    ("the keypad no longer reacts", "troubleshooting"),
    ("network connection drops every few minutes", "troubleshooting"),
    ("what caused alarm code L2", "troubleshooting"),
    ("the repeater gets hot and loses transmission", "troubleshooting"),
    ("forward power alarm keeps returning", "troubleshooting"),
    ("BR310 has power but the display stays blank", "troubleshooting"),
    ("incoming calls cannot be heard", "troubleshooting"),
    ("status LED alternates red and orange", "troubleshooting"),
    ("why did reception suddenly disappear", "troubleshooting"),
    ("unit makes a clicking sound during transmit", "troubleshooting"),
    ("the ethernet port is not detected", "troubleshooting"),
    ("startup freezes at the logo", "troubleshooting"),
    ("repeeter wont recieve any signal", "troubleshooting"),
    ("fan alarm after ten minutes", "troubleshooting"),
    ("nothing happens when the power button is pressed", "troubleshooting"),
    ("audio level keeps rising and falling", "troubleshooting"),
    ("why are both timeslot indicators stuck on", "troubleshooting"),

    # comparison (30)
    ("compare DR450 with MR850 for rack deployment", "comparison"),
    ("is the CR720 lighter than the BR310", "comparison"),
    ("which model offers the wider temperature range", "comparison"),
    ("contrast their rear panel connectors", "comparison"),
    ("are the installation tools identical for the two units", "comparison"),
    ("DR450 or MR850 which supports more channels", "comparison"),
    ("show differences in power consumption across both repeaters", "comparison"),
    ("which one is easier to wall mount", "comparison"),
    ("compare how each device handles fan alarms", "comparison"),
    ("do these models require equal input voltage", "comparison"),
    ("side by side specifications for CR720 and BR310", "comparison"),
    ("which of the pair includes a duplexer", "comparison"),
    ("are their cleaning requirements equivalent", "comparison"),
    ("MR850 against DR450 for an indoor cabinet", "comparison"),
    ("what advantages does the first have over the second", "comparison"),
    ("evaluate both devices for a compact installation", "comparison"),
    ("how do their alarm indicators differ", "comparison"),
    ("which product has the higher output rating", "comparison"),
    ("does one ship with more mounting parts than the other", "comparison"),
    ("CR720 v BR310", "comparison"),
    ("comapre the DR450 to the MR850", "comparison"),
    ("are both repeaters rated for the same environment", "comparison"),
    ("tell me which unit is more appropriate for wall installation", "comparison"),
    ("differences in antenna connections across the two models", "comparison"),
    ("which one should be selected for lower power use", "comparison"),
    ("compare what arrives in each package", "comparison"),
    ("do they use an identical shutdown procedure", "comparison"),
    ("how does MR850 mounting differ from DR450 mounting", "comparison"),
    ("which of these products supports battery operation", "comparison"),
    ("weigh their troubleshooting capabilities against each other", "comparison"),

    # standard (30)
    ("state the dimensions of the DR450", "standard"),
    ("which frequency band does MR850 cover", "standard"),
    ("is a grounding cable supplied", "standard"),
    ("how many channels can the unit store", "standard"),
    ("does CR720 support an external battery", "standard"),
    ("name the indicators on the front panel", "standard"),
    ("where is the ethernet connector located", "standard"),
    ("give the allowed humidity range", "standard"),
    ("is BR310 suitable for outdoor installation", "standard"),
    ("what type of fuse is specified", "standard"),
    ("does the package contain rack handles", "standard"),
    ("who produces the DR450", "standard"),
    ("what color is the analog mode indicator", "standard"),
    ("is encryption mentioned for this product", "standard"),
    ("provide the rated DC current", "standard"),
    ("what does the rear accessory port connect to", "standard"),
    ("can MR850 operate without mains power", "standard"),
    ("list all items in the carton", "standard"),
    ("what are the low and high transmit settings", "standard"),
    ("is there a separate receive antenna socket", "standard"),
    ("what distinguishes timeslot one from timeslot two", "standard"),
    ("are both RF connectors type N", "standard"),
    ("does the display show channel numbers", "standard"),
    ("maximum storage temperature?", "standard"),
    ("weight of CR720", "standard"),
    ("wht voltage is required by BR310", "standard"),
    ("number of screws included", "standard"),
    ("is alcohol permitted for cleaning", "standard"),
    ("what material are the mounting plates made from", "standard"),
    ("does this repeater comply with IP67", "standard"),
]
