"""Retired v2 acceptance set (macro-F1=0.852; rejected)."""

RETIRED_INTENT_CASES_V2 = [
    # procedural (20)
    ("provide directions for installing the ZX410 in a cabinet", "procedural"),
    ("what sequence connects the backup supply", "procedural"),
    ("talk me through setting a transmit frequency", "procedural"),
    ("procedure for fastening the antenna feed", "procedural"),
    ("how can the QN730 be returned to factory settings", "procedural"),
    ("steps to prepare the chassis for rack mounting", "procedural"),
    ("explain the way to replace a cooling fan", "procedural"),
    ("what actions turn off the status display", "procedural"),
    ("need guidance connecting the ground wire", "procedural"),
    ("how should a new network address be entered", "procedural"),
    ("show me the correct power-up sequence", "procedural"),
    ("instructions to switch the MX260 into digital operation", "procedural"),
    ("how is the duplexer fixed inside the enclosure", "procedural"),
    ("method for setting the receive channel", "procedural"),
    ("how can I remove and reinstall the rear cover", "procedural"),
    ("setup guide for an external antenna", "procedural"),
    ("wat steps configure the output level", "procedural"),
    ("tell me how to attach the wall plate", "procedural"),
    ("what is required to enable the keypad lock", "procedural"),
    ("describe how the unit is safely disconnected", "procedural"),

    # troubleshooting (20)
    ("ZX410 repeatedly loses its programmed channels", "troubleshooting"),
    ("the receive indicator is lit but there is no sound", "troubleshooting"),
    ("why does alarm F4 return after a reset", "troubleshooting"),
    ("QN730 becomes extremely hot while idle", "troubleshooting"),
    ("the RF connector is no longer recognized", "troubleshooting"),
    ("transmissions break up every few seconds", "troubleshooting"),
    ("unit has voltage but refuses to boot", "troubleshooting"),
    ("both channel LEDs remain frozen", "troubleshooting"),
    ("MX260 reports low forward power", "troubleshooting"),
    ("why has the useful range decreased", "troubleshooting"),
    ("display characters are corrupted", "troubleshooting"),
    ("a loud hum appears during reception", "troubleshooting"),
    ("ethernet link disconnects under load", "troubleshooting"),
    ("device turns itself off when transmitting", "troubleshooting"),
    ("the alarm light stays red after startup", "troubleshooting"),
    ("no response from any front-panel key", "troubleshooting"),
    ("reception works but transmission has stopped", "troubleshooting"),
    ("fan speed rises and falls continuously", "troubleshooting"),
    ("repeatr is stuck on the boot screen", "troubleshooting"),
    ("what is causing repeated fuse failure", "troubleshooting"),

    # comparison (20)
    ("ZX410 versus QN730 for a narrow equipment room", "comparison"),
    ("which of the two models consumes less energy", "comparison"),
    ("are their included mounting kits equivalent", "comparison"),
    ("contrast the alarm behavior of both devices", "comparison"),
    ("does MX260 offer anything that LK880 does not", "comparison"),
    ("which product is the stronger choice for wall mounting", "comparison"),
    ("compare the connector layouts on ZX410 and QN730", "comparison"),
    ("is one unit rated for a broader temperature span", "comparison"),
    ("how are the two maintenance procedures different", "comparison"),
    ("show what is supplied with each repeater", "comparison"),
    ("which device provides more RF output", "comparison"),
    ("do they need the same installation tools", "comparison"),
    ("MX260 compared with LK880", "comparison"),
    ("what separates these products in daily operation", "comparison"),
    ("are identical antenna sockets used by both", "comparison"),
    ("choose between ZX410 and QN730 for battery use", "comparison"),
    ("compare their physical size and mass", "comparison"),
    ("which member of the pair has simpler grounding", "comparison"),
    ("does either model include better environmental sealing", "comparison"),
    ("diferences between MX260 and LK880 accessories", "comparison"),

    # standard (20)
    ("give the nominal supply voltage of ZX410", "standard"),
    ("is QN730 delivered with an antenna cable", "standard"),
    ("how many programmable keys are available", "standard"),
    ("identify the socket beside the fuse holder", "standard"),
    ("does MX260 carry an IP rating", "standard"),
    ("state its maximum permitted humidity", "standard"),
    ("which company builds the LK880", "standard"),
    ("is wall installation allowed for this unit", "standard"),
    ("what items are supplied in the mounting kit", "standard"),
    ("does it accept a separate receive antenna", "standard"),
    ("list the available transmit power settings", "standard"),
    ("what is the purpose of the orange indicator", "standard"),
    ("can the enclosure be cleaned using ethanol", "standard"),
    ("where can the serial number be found", "standard"),
    ("is an AC adapter included as standard", "standard"),
    ("what differentiates digital mode from analog mode", "standard"),
    ("maximum number of stored channels", "standard"),
    ("does the device satisfy IP54 requirements", "standard"),
    ("wht is the mass of QN730", "standard"),
    ("are both timeslot lights blue", "standard"),
]
