model_list:

  - model_name: llama3.2-3b
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://host.docker.internal:11434

  - model_name: qwen2.5-7b
    litellm_params:
      model: ollama/qwen2.5:7b
      api_base: http://host.docker.internal:11434

  - model_name: deepseek-r1-8b
    litellm_params:
      model: ollama/deepseek-r1:8b
      api_base: http://host.docker.internal:11434

  - model_name: bge-m3
    litellm_params:
      model: ollama/bge-m3
      api_base: http://host.docker.internal:11434
    model_info:
      mode: embedding

litellm_settings:
  drop_params: true
  set_verbose: false
